name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: 1.1.0
  google_generative_ai:
  dart_frog_web_socket:
  envied: ^0.5.4+1
  models:
    path: ../packages/models
  uuid:

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
